swagger: '2.0'
info:
  title: Hello World REST API
  description: REST API that returns Hello World json object
  version: '1.0'
paths:
  /:
    get:
      description: Returns Hello World in a json object
      produces:
      - application/json
      responses:
        '200':
          description: Hello World
          schema:
            type: object
            properties: 
              ReturnVal:
                type: string